# Generated by Django 3.1.1 on 2021-01-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intereses',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipoCuenta',
            field=models.CharField(default='basico', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='tipoUsuario',
            field=models.CharField(default='basico', max_length=45),
        ),
    ]
