# Generated by Django 3.1.1 on 2021-01-15 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intereses',
            field=models.CharField(blank=True, default='dato desde consola', max_length=45),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='alerta',
            fields=[
                ('idAlerta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreAlerta', models.CharField(max_length=50)),
                ('palabrasClave', models.CharField(max_length=50)),
                ('organoUno', models.CharField(max_length=50)),
                ('organoDos', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaBorrada', models.DateField(auto_now=True)),
                ('statusAlerta', models.CharField(max_length=50)),
                ('precision', models.CharField(max_length=50)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
