# Generated by Django 3.1.1 on 2021-01-19 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210115_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('idContenido', models.AutoField(primary_key=True, serialize=False)),
                ('cont', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DescargaNotaDOF',
            fields=[
                ('idDescargaNotaDOF', models.AutoField(primary_key=True, serialize=False)),
                ('codNota', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('codOrga1', models.CharField(max_length=50)),
                ('codOrga2', models.CharField(max_length=50)),
                ('pagina', models.CharField(max_length=50)),
                ('codSeccion', models.CharField(max_length=50)),
                ('existePDF', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('idSecretaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSecretaria', models.CharField(max_length=50)),
                ('tipoSecretaria', models.CharField(max_length=50)),
                ('estadoSecretaria', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='organoDos',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='organoUno',
            new_name='subcategoria',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='idAlerta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='intereses',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPago', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraEnvio',
            fields=[
                ('idBitacora', models.AutoField(primary_key=True, serialize=False)),
                ('statusBitacora', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('nombreAlerta', models.CharField(max_length=50)),
                ('bitacoraEnvioCol', models.CharField(max_length=50)),
                ('idAlerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alerta')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvisoSitio',
            fields=[
                ('idAvisos', models.AutoField(primary_key=True, serialize=False)),
                ('textoAviso', models.CharField(max_length=50)),
                ('statusAviso', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaHasContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificado', models.CharField(max_length=50)),
                ('alertaHasContenidocol', models.CharField(max_length=50)),
                ('idAlertaContenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alerta')),
                ('idContenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contenido')),
            ],
        ),
    ]
