# Generated by Django 3.1.1 on 2021-01-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210118_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fechaBorrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='descarganotadof',
            name='existePDF',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
