# Generated by Django 3.1.1 on 2021-01-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210118_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarganotadof',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
