# Generated by Django 3.1.1 on 2021-01-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210118_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarganotadof',
            name='titulo',
            field=models.TextField(null=True),
        ),
    ]
