# Generated by Django 3.1.1 on 2021-01-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210118_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarganotadof',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
